### ISSUE TITLE
Nested <form> every time the form is submitted 

### ISSUE THREAD

**Issue by donMichaelL** [guettli/django-htmx-fun#1]
Every time the form is submitted a new nested `<form>` element is created 
<form hx-post="/create_note_hxpost" class="">  

    <form hx-post="/create_note_hxpost" class="">  

        <form hx-post="/create_note_hxpost" class="">  

            <form hx-post="/create_note_hxpost" class="">  

                <form hx-post="/create_note_hxpost">

**Comment by guettli** [comment]
Thank you! I will have a look at this.
